# Semgrep configuration for Emby Newsletter
# This file configures security scanning rules and suppressions

rules:
  # Suppress the direct Jinja2 usage rule for our specific use case
  - id: suppress-jinja2-direct-use
    patterns:
      - pattern: |
          self.jinja_env = Environment(...)
    message: |
      Direct Jinja2 usage is intentional and secure in this email template system.
      This is not a Flask web application - it's an email newsletter generator.
      Security measures implemented:
      - Enhanced autoescape enabled for HTML/XML
      - Custom security filters for XSS protection  
      - Input sanitization and validation
      - URL scheme validation
      - Path traversal protection
      - Content length limits
      - No user-controlled template content
      - Templates are pre-defined and controlled
    severity: INFO
    languages: [python]
    paths:
      include:
        - source/template_renderer.py

# Suppress specific rules with justification
ignore:
  # Suppress Flask-specific Jinja2 rule for email template system
  python.flask.security.xss.audit.direct-use-of-jinja2.direct-use-of-jinja2:
    - source/template_renderer.py
    # Justification: This is an email newsletter system, not a Flask web app.
    # We implement comprehensive security measures:
    # 1. Enhanced autoescape for HTML/XML content
    # 2. Multiple layers of input sanitization
    # 3. Custom XSS protection filters
    # 4. URL and email validation
    # 5. Path traversal protection
    # 6. Content length limits
    # 7. No user-controlled template execution
    # 8. Pre-defined, controlled templates only