version: '3.8'

services:
  emby-newsletter:
    image: ghcr.io/j0n4e/emby-newsletter:latest
    container_name: emby-newsletter
    volumes:
      - ./config:/app/config:ro
      - ./templates:/app/templates:ro
    environment:
      - TZ=Europe/Paris
      # PUID and PGID will be automatically inherited from Unraid variables
    restart: unless-stopped
    # Remove user restriction to allow cron to run as root
    # user: "99:100"
    read_only: false  # Allow writes for cron
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp