version: '3.8'

services:
  emby-newsletter:
    image: ghcr.io/j0n4e/emby-newsletter:latest
    container_name: emby-newsletter
    volumes:
      - ./config:/app/config:ro
      - ./templates:/app/templates:ro
    environment:
      - TZ=Europe/Paris  # Change this to your timezone
      # PUID=99 and PGID=100 are set in Unraid docker variables
    restart: unless-stopped
    user: "99:100"       # Standard Unraid user:group
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /var/log
      - /var/run:rw,noexec,nosuid,size=100m  # For cron PID file
      - /var/spool/cron:rw,noexec,nosuid,size=10m  # For cron jobs