version: '3.8'

services:
  mediaserver-newsletter:
    container_name: emby-newsletter
    image: 'ghcr.io/j0n4e/emby-newsletter:latest'
    environment:
      USER_UID: 1000
      USER_GID: 1000
      TZ: 'Europe/Bucharest'
    volumes:
      - './config:/app/config'