version: '3.8'

services:
  emby-newsletter:
    image: ghcr.io/j0n4e/emby-newsletter:latest
    container_name: emby-newsletter
    volumes:
      - ./config:/app/config:ro
      - ./templates:/app/templates:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    user: "0:0"
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
      - /var/log:rw,nosuid,size=50m
      - /var/run:rw,noexec,nosuid,size=50m
      - /var/spool:rw,nosuid,size=20m
      - /var/spool/cron:rw,nosuid,size=10m
      - /root:rw,noexec,nosuid,size=10m