version: '3.8'

services:
  emby-newsletter:
    image: ghcr.io/j0n4e/emby-newsletter:latest
    container_name: emby-newsletter
    volumes:
      - ./config:/app/config:ro
      - ./templates:/app/templates:ro
    restart: unless-stopped
    user: "0:0"          # Run as root for cron access
    read_only: true      # Keep read-only for security
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
      - /var/log:rw,noexec,nosuid,size=50m
      - /var/run:rw,noexec,nosuid,size=50m
      - /var/spool:rw,noexec,nosuid,size=10m
      - /var/spool/cron:rw,noexec,nosuid,size=5m
      - /root:rw,noexec,nosuid,size=10m