version: '3.8'

services:
  emby-newsletter:
    image: ghcr.io/j0n4e/emby-newsletter:latest
    container_name: emby-newsletter
    volumes:
      - ./config:/app/config:ro
      - ./templates:/app/templates:ro
    environment:
      - TZ=Europe/Paris  # Change this to your timezone
      - PUID=1000        # Change this to your user ID
      - PGID=1000        # Change this to your group ID
    restart: unless-stopped
    user: "1000:1000"    # Change this to your user:group IDs
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /var/log