jellyfin:
  url: ""
  api_token: ""
  watched_film_folders:
    - ""
  watched_tv_folders:
    - ""
  
  observed_period_days: 30

tmdb:
  api_key: ""


email_template:
  language: "en"
  subject: ""
  title: ""
  subtitle: ""
  jellyfin_url: ""
  unsubscribe_email: ""
  jellyfin_owner_name: ""


email:
  smtp_server: ""
  smtp_port: 
  smtp_username: ""
  smtp_password: ""
  smtp_sender_email: ""

recipients:
  - ""
