### Example configuration file.
## All values are mandatory, except for the ones that are commented out.


jellyfin:
  
  # URL of your jellyfin server
  url: ""
  
  # API token of your jellyfin server. See How To in the repository README.
  api_token: ""
  
  # List of folders to watch for new movies. 
  # You can find them in your Jellyfin Dashboard -> Libraries -> Select a library -> Folder **WITHOUT THE TRAILING /**
  watched_film_folders:
    # example for /movies folder add "movies"
    - ""
  
  # List of folders to watch for new movies. 
  # You can find them in your Jellyfin Dashboard -> Libraries -> Select a library -> Folder **WITHOUT THE TRAILING /**
  watched_tv_folders:
    - ""
    # example for /movies folder add "movies"
  
  # Number of days to look back for new items
  observed_period_days: 30

tmdb:
# TMDB API key. See How To in the repository README.
  api_key: ""

# Email template to use for the newsletter
# You can use placeholders to dynamically insert values. See available placeholders here : https://github.com/SeaweedbrainCY/jellyfin-newsletter/wiki/How-to-use-placeholder
email_template:
  # Language of the email. Supported languages are "en" and "fr".
  language: "en"

  # Subject of the email
  subject: ""

  # Title of the email
  title: ""

  # Subtitle of the email
  subtitle: ""

  # Will be used to redirect the user to your Jellyfin instance
  jellyfin_url: ""

  # Used in the footer. This is a legal notice.
  unsubscribe_email: ""

  # Used in the footer
  jellyfin_owner_name: ""


email:
  # SMTP server configuration. TLS is required for now.
  smtp_server: ""
  smtp_port: 
  smtp_username: ""
  smtp_password: ""
  smtp_sender_email: ""

# List of users to send the newsletter to.
recipients:
  # Example : "fname@email.com" or "fname <fname@email.com">
  - ""
