### Example configuration file.
## All values are mandatory, except for the ones that are commented out.


jellyfin:
    # URL of your jellyfin server
    url: "" 

    # API token of your jellyfin server, see requirements for more info
    api_token: ""

    # List of folders to watch for new movies 
    # You can find them in your Jellyfin Dashboard -> Libraries -> Select a library -> Folder **WITHOUT THE TRAILING /**
    watched_film_folders:
        - ""
        # example for /movies folder add "movies"


    # List of folders to watch for new shows
    # You can find them in your Jellyfin Dashboard -> Libraries -> Select a library -> Folder **WITHOUT THE TRAILING /**
    watched_tv_folders:
        - ""
        # example for /tv folder add "tv"
  
  # Number of days to look back for new items
  observed_period_days: 30

tmdb:
    # TMDB API key, see requirements for more info
    api_key: ""

# Email template to use for the newsletter
# You can use placeholders to dynamically insert values. See available placeholders here : https://github.com/SeaweedbrainCY/jellyfin-newsletter/wiki/How-to-use-placeholder
email_template:
    # Language of the email, supported languages are "en" and "fr"
    language: "en"
    # Subject of the email
    subject: ""
    # Title of the email
    title: ""
    # Subtitle of the email
    subtitle: ""
    # Will be used to redirect the user to your Jellyfin instance
    jellyfin_url: ""
    # For the legal notice in the footer
    unsubscribe_email: ""
    # Used in the footer
    jellyfin_owner_name: ""

# SMTP server configuration, TLS is required for now
# Check your email provider for more information
email:
    # Example: GMail: smtp.gmail.com
    smtp_server: ""
    # Usually 587
    smtp_port: 
    # The username of your SMTP account
    smtp_username: ""
    # The password of your SMTP account
    smtp_password: ""
    # Example: "jellyfin@example.com" or to set display username "Jellyfin <jellyfin@example.com">
    smtp_sender_email: ""


# List of users to send the newsletter to
recipients:
  - ""
  # Example: "name@example.com" or to set username "Name <name@example.com">
